### ISSUE TITLE
Used in so-and-so sites

### ISSUE THREAD

**Issue by bennylin** [rene78/PopComPics#7]
I think "sites" should be changed to "pages". Some of my top files are only used in (hundreds of pages in) a single Wikisource, for example, definitely not multiple "sites" or projects.

**Comment by rene78** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/36115705/186940866-7ed866fb-7e7e-4bfa-a420-9d8e5fb71533.png)
Already like you are proposing, I would say?

**Comment by rene78** [comment]
Ah, got it! You mean this!
![image](https://user-images.githubusercontent.com/36115705/186942104-4e08e778-e1dc-45c4-82cf-b328543a0094.png)
Gonna change it.
Thanks!
